version: '3.8'

services:
  secretary-app:
    image: secretary-app:latest
    env_file: .env.docker
    ports:
      - "80:5100"
    volumes:
      - secretary_user_data:/app/app/user_data
      - secretary_logs:/app/logs
    restart: unless-stopped
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5100/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - secretary-app
    restart: unless-stopped

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: secretary
      POSTGRES_PASSWORD: secretary
      POSTGRES_DB: secretary_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  secretary_user_data:
  secretary_logs:
  postgres_data:
