version: '3.8'

services:
  secretary-app:
    container_name: secretary-app-prod
    image: playermmcm/secretary-app:latest
    volumes:
      - user_data:/app/app/user_data
      - logs:/app/logs
    restart: unless-stopped
    depends_on:
      - postgres
    # command: tail -f /dev/null
    environment:
      MODE: ${MODE}
      HOST: ${HOST}
      SERVER_PORT: ${SERVER_PORT}
      SECRET_KEY: ${SECRET_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      AI_WEBHOOK_URL: ${AI_WEBHOOK_URL}
      AI_IMAGE_WEBHOOK_URL: ${AI_IMAGE_WEBHOOK_URL}
      SESSION_COOKIE_SECURE: ${SESSION_COOKIE_SECURE}
      SESSION_COOKIE_HTTPONLY: ${SESSION_COOKIE_HTTPONLY}
      PERMANENT_SESSION_LIFETIME: ${PERMANENT_SESSION_LIFETIME}
      DATABASE_URL: ${DATABASE_URL}

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5100/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.secretary.rule=Host(`tasks.ndomen.online`)"
      - "traefik.http.routers.secretary.entrypoints=web, websecure"
      - "traefik.http.routers.secretary.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.secretary.tls=true"
      - "traefik.http.services.secretary.loadbalancer.server.port=5100"
    networks:
      - n8n_with_https_default

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: secretary
      POSTGRES_PASSWORD: secretary
      POSTGRES_DB: secretary_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - n8n_with_https_default

volumes:
  user_data:
  logs:
  pg_data:

networks:
  n8n_with_https_default:
    external: true
