"""add task_overrides table

Revision ID: 3fe69177d4bd
Revises: d47fd68c189e
Create Date: 2025-07-12 15:29:41.330456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fe69177d4bd'
down_revision = 'd47fd68c189e'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('task_overrides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['productivity.tasks.TaskID'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='productivity'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_overrides', schema='productivity')
    # ### end Alembic commands ###
