"""empty message

Revision ID: e49094ff8df7
Revises: b5d6f6ec283d
Create Date: 2025-08-06 22:06:46.782121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e49094ff8df7'
down_revision = 'b5d6f6ec283d'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema='users') as batch_op:
        batch_op.alter_column('user_name',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_constraint('users_user_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema='users') as batch_op:
        batch_op.create_unique_constraint('users_user_name_key', ['user_name'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('user_name',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###

