"""add index to TaskOverride

Revision ID: ff0e7dea0f9d
Revises: 9800d6174958
Create Date: 2025-07-14 12:55:28.601805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff0e7dea0f9d'
down_revision = '9800d6174958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_overrides', schema='productivity') as batch_op:
        batch_op.create_index('idx_task_overrides_taskid_date_userid', ['task_id', 'date', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_overrides', schema='productivity') as batch_op:
        batch_op.drop_index('idx_task_overrides_taskid_date_userid')
    # ### end Alembic commands ###
