name: Release Workflow

on:
  # push:
  #   tags:
  #     - 'v*.*.*' # More specific tag pattern, can be adjusted to 'v*' if needed
  workflow_dispatch: # Добавляем ручной запуск
    inputs:
      build_and_push_docker:
        description: 'Build and push Docker image?'
        type: boolean
        required: false
        default: false

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Needed for pushing to GitHub Packages, if applicable
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/secretary-app # Using GitHub Container Registry
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install client dependencies
        working-directory: ./client
        run: npm install

      - name: Build client
        working-directory: ./client
        run: npm run build

      - name: Copy client dist to server/app/static # Assuming 'static' is correct
        run: |
          rm -rf server/app/static || true
          mkdir -p server/app/static
          cp -a client/dist/. server/app/static/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile # Assuming 'Dockerfile' is correct
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/secretary-app:${{ github.ref_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/secretary-app:latest
